services:
  - type: web
    name: some-test254-api
    env: node
    region: oregon
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm run migrate:up && npm start
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 8080
      - key: DATABASE_URL
        fromDatabase:
          name: movies-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRES_IN
        value: 7d
      - key: PASSWORD_PEPPER
        generateValue: true
      - key: OMDB_API_KEY
        sync: false

databases:
  - name: movies-db
    databaseName: movies
    user: movies_user
    plan: free
    region: oregon
