services:
  - type: web
    name: some-test254-api
    env: node
    region: oregon
    plan: free
    buildCommand: npm install && npm run build
    startCommand: ./start.sh
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 8080
      - key: DATABASE_URL
        fromDatabase:
          name: movies-db
          property: connectionString
      - key: CORS_ORIGIN
        value: "*"
      - key: JWT_SECRET
        sync: false
      - key: JWT_EXPIRES_IN
        value: 7d
      - key: PASSWORD_PEPPER
        sync: false
      - key: OMDB_API_KEY
        sync: false
      - key: RATE_LIMIT_WINDOW_MS
        value: "60000"
      - key: RATE_LIMIT_MAX
        value: "120"
      - key: CACHE_TTL_HOURS
        value: "24"

databases:
  - name: movies-db
    databaseName: movies
    user: movies_user
    plan: free
    region: oregon
